% Geographical data for South America to be used with cmap.pl

country(antilles).
country(bolivia).
country(columbia).
country(ecuador).
country(guyana).
country(peru).
country(uruguay).
country(argentina).
country(brazil).
country(chile).
country(french_guiana).
country(paraguay).
country(surinam).
country(venezuela).

beside(antilles,venezuela).
beside(argentina,brazil).
beside(argentina,paraguay).
beside(bolivia,brazil).
beside(bolivia,paraguay).
beside(brazil,columbia).
beside(brazil,guyana).
beside(brazil,peru).
beside(brazil,uruguay).
beside(chile,peru).
beside(columbia,peru).
beside(ecuador,peru).
beside(guyana,surinam).
beside(argentina,bolivia).
beside(argentina,chile).
beside(argentina,uruguay).
beside(bolivia,chile).
beside(bolivia,peru).
beside(brazil,french_guiana).
beside(brazil,paraguay).
beside(brazil,surinam).
beside(brazil,venezuela).
beside(columbia,ecuador).
beside(columbia,venezuela).
beside(french_guiana,surinam).
beside(guyana,venezuela).
